### PR TITLE
Add support for raw HTML nodes.

### PR DESCRIPTION
**Pull request by tomdale**
In XML, CDATA nodes can be used to include portions of unescaped text. HTML does not have any facility for this because it is typically not required.

However, in the case of SimpleDOM (and specifically Ember’s FastBoot), the DOM tree is just an intermediate representation of the final serialized HTML output. In some cases, users may want to put snippets of unescaped HTML into that DOM tree for delivery to the user.

One option is to parse the unescaped HTML provided by the user and turn that into DOM nodes in the intermediate DOM tree. However, this incurs a performance cost for little gain, as we parse the provided HTML, store it as a tree of nodes, then reserialize that tree immediately afterwards when the entire document is being serialized.

By providing a CDATA mechanism, we can allow consumers of SimpleDOM to “stash” unparsed HTML in the tree, which is then re-emitted without parsing when that tree is serialized.

### CODE REVIEW

**Comment by tomdale** [comment]
I've reconsidered whether trying to use the CDATA API is a good idea. For now, let's create a custom extension that avoids the uncanny valley problem and makes the use case more explicit. This is also less likely to conflict with potential future use cases that want to legitimately use CDATA (although I doubt that day will ever come to pass).

**Comment by tomdale** [comment]
I changed the name of the PR to reflect the above change. :arrow_up:

**Comment by krisselden** [comment]
Can you change the remaining cdata bits to raw?

**Comment by krisselden** [comment]
Otherwise looks good to me

**Comment by tomdale** [comment]
@krisselden I force-pushed a commit that should remove all references to CDATA, did I miss any?

**Comment by tomdale** [comment]
Oops, forgot to push.

**Pull request merged**
